# -*- coding: utf-8 -*-
"""FinalImage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/189xhdlUGORIIfzxxP9E7RXSZNKOD_Pz4
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

import requests
from bs4 import BeautifulSoup
import os
import urllib.request

url = "https://www.nirfindia.org/2022/EngineeringRanking.html"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

# Extract all links from the webpage
links = [a["href"] for a in soup.find_all("a", href=True)]

# Filter redirectable links by checking if the links start with "http"
redirectable_links = [link for link in links if link.startswith("http")]

# Filter links that end with ".png"
png_links = [link for link in redirectable_links if link.endswith(".png")]

# Create a folder to save the images
folder_name = "22images"
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

# Download and save the images
counter = 1  # Initialize the counter
for link in png_links:
    filename = f"{counter}.png"  # Set the filename to the counter value plus the .png extension
    urllib.request.urlretrieve(link, f"{folder_name}/{filename}")  # Download the image and save it with the filename
    counter += 1  # Increment the counter for the next image

import os
from PIL import Image
import re
import pandas as pd
path='/content/22images'
df = pd.DataFrame({col: [] for col in range(1,19)})


k=0
for filename in sorted(os.listdir(path)):
    # Check if the file is a text file
    if filename.endswith('.png'):
        # Open the file for reading
         with Image.open(os.path.join(path, filename)) as img:
           imagename = os.path.basename(filename)
           extractedInformation = pytesseract.image_to_string(img)
           count=0;
           for i in range(0,len(extractedInformation)):
              if (extractedInformation[i]=='|' and extractedInformation[i+3]=='c'):
                count+=1    
                if(count==1):
                  print(extractedInformation[i+3])
                  break;

           print(i)
           final=i+7
           l=len(extractedInformation)
           for i in range(final,l-1):
              print(extractedInformation[i])
              if(extractedInformation[i]=='\n'):
                endway=i
                print(endway)
                break;
           use_string = extractedInformation[final:endway]
           print(use_string)
           length=len(use_string)
           print(length)
           parts=use_string.split(' ')
           parts[0]=imagename
           pattern = r"[^\d\.\s]"
           clean_parts = re.sub(pattern, "", str(parts))
           clean_parts=clean_parts.split(' ')
           lp=len(clean_parts )
           for i in range(1,lp):
             if(clean_parts[i]==''):
               for j in range(i,lp-1):
                 clean_parts[j]=clean_parts[j+1]
           final=clean_parts[0:18]
           print(final) 
           #df.loc[k] = clean_parts 
           print(lp)
           print(clean_parts)
           print(len(final))
           print(final)
           if(len(final)==18):
            df.loc[k] = final
           k+=1
        

            # Output the resulting dataframe
           print(df)

df.to_csv('data22.csv', index=False)